### ISSUE TITLE
エンディングのメッセージを書く

### ISSUE THREAD

**Issue by Se1getsu** [prapro-ou/pizza-delivery#105]
endings.mjsのendingMessageを全て書く

**Comment by yuiyyui** [comment]
・重症エンド
店長：	　なんか体ボロボロじゃないか？
主人公：　...大丈夫..です。
	　バタンッ!
　　　　　主人公は病院に運ばれ、全治三ヶ月の怪我を負った。
　

・入院エンド
店長：　　なんか顔色悪くないか？
主人公：　そんなこと...ウッ
　　　　　バタンッ!
　　　　　密かにゲテモノピザを味見していた主人公はお腹をこわし、病院に運ばれた。


・ピザ生地の冷めた日エンド(旧ピザ生地冷めちゃったエンド)
店長：　　届けるのが遅すぎるよ。
　　　　　せっかくの熱々なピザ生地が台無しじゃないか！
主人公：　すみません。
　　　　　その日からピザに対する情熱も冷め、アルバイトを辞めた。	


・パーフェクトエンド
店長：　　君宛にこんな手紙が届いているぞ。
　　　　　"Congratulations! ここまで遊んでくれてありがとう!"
　　　　　よく分らんが、優秀な部下を持って私も鼻が高いよ。
　　　　　

・素材の味エンド
店長：　　トッピング無しの状態でお客様に提供したようだな。
　　　　　...
　　　　　よく分かっているじゃないか。
　　　　　一番おいしいのはピザ生地そのものなんだよ。
　　　　　そもそもトッピングを乗せるピザは好きじゃないんだよ。異なる食感、風味のものをごてごてと。あれじゃピザ　　　　生地の繊細な味わいが台無しだよ。ピザ生地をただのパンだと思ってる人が多いが、実はものすごく深い！それぞれの特性がピザ全体のクオリティを決めている。水分量、厚さ、焼く温度で異なる姿を演じ、...
           とにかくこの調子でピザ生地本来のよさを広めていってくれ。
主人公：　(もしかしてそのためにわざと食材を捨てたりとか...ないよな)


・海の家エンド
店長：　　魚介系のピザをたくさん作ったようだな。
　　　　　そんな君に知り合いが経営している海の家で
　　　　　得意のシーフートピザを振舞ってもらえないか？
主人公：　ぜひ！



・本場リスペクトエンド(旧イタリア人ブチギレエンド)
店長：　　ワタシノボコクノピッツァノミリョクヲ
　　　　　イロイロナヒト二ヒロメテクレタヨウダネ。
　　　　　アリガトウ。
主人公：　そういえば店長イタリア人だった。



・イタリア修行エンド
店長：　　スバラシイシゴトブリダッタ。
　　　　　ワタシノボコクイタリアデピザノ
　　　　　シュギョウスルキハナイ？
主人公：　海外はちょっと。
店長：　　キョヒケンハアリマセーン。
　　　　　イマカライキマショーウ。
主人公：　ひえー。



・ピザ博士エンド
店長：　　よくこんなにピザの種類を知ってたね。
主人公：　はい。ピザ屋のアルバイターですから。
	　(適当に作ったなんて言えない。)



・満腹エンド
主人公：　その前に僕からいいですか？
店長：　　よかろう。何でも言ってくれ。
主人公：　なんか前より太ってませんか？
店長：　　君がたくさんピザを作っているところを見るとおなかがすいてね。
　　　　　もぉう食べられないよぉ。
主人公：　何やってんだこの人。　



・社員エンド
店長：　　よくこの危機的状況を乗り越えてくれた。
　　　　　是非とも社員になってくれ。
主人公：　ありがとうございます。



・クビエンド
店長：　　お客様からクレームがたくさん来ているぞ。
　　　　　店の信頼はダダ下がりだ。
　　　　　明日から来なくていいよ。
主人公：　そんな！やはり僕には向いてないのか。
　　　　　その後主人公の精神は病み、家から出ることは無かった。

**Comment by Se1getsu** [comment]
ありがとうございます！ PRお願いします！

**Comment by yuiyyui** [comment]
素材の味エンドの"そもそも"から"異なる姿を演じ、..."の部分は文字の大きさをかなり小さくすることでオタク感を出しながら画面に入るように調節したいと思っています。

**Comment by yuiyyui** [comment]
なんか改善点などあればお願いします。

**Comment by Se1getsu** [comment]
とても良いと思います！ 気になった点としては...
-  「ピザ生地の冷めた日エンド」と「クビエンド」がちょっとガチ感出てるのでもう少しギャグテイストにした方がいいかもですね。
- 店長がカタカナで喋るところは読みづらいので文節ごとにスペースを入れると良いかもしれません！
- 社員エンドの危機的状況についての説明があった方がいいかもです。食材盗まれたことは店長知ってるんですかね？

**Comment by yuiyyui** [comment]
了解です。参考に直してみます。
