### ISSUE TITLE
スロット選択画面にスロットの概要を書く

### ISSUE THREAD

**Issue by Se1getsu** [prapro-ou/pizza-delivery#61]
if スロットがない -> "空"
else if 既にエンディングを見ている -> エンディングの名前
else ->  どのステージまで解放してるか

Slot.mjsにどのステージまで解放してるかを返すメソッドを作ると良いかも
if stageResultsが空 -> 1
else → stageResults[i].stage.stageNumber の最大値

**Comment by Westa710** [comment]
スロットが空きでない場合はalertを出して警告する
